CoreBB/Models/User/LogInViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace CoreBB.Web.Models.User
{
    public class LogInViewModel
    {
        [Required, DisplayName("Name")]
        public string Name { get; set; }

        [Required, DisplayName("Password")]
        public string Password { get; set; }
    }
}

CoreBB/Models/User/RegisterViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace CoreBB.Web.Models.User
{
    public class RegisterViewModel
    {
        [Required, DisplayName("Name")]
        public string Name { get; set; }
        [Required, DisplayName("Password")]
        public string Password { get; set; }
        [Required, DisplayName("Repeat Password")]
        public string RepeatPassword { get; set; }
        [Required, DisplayName("Self-Introduction")]
        public string Description { get; set; }
    }
}

CoreBB/Models/User/UserEditViewModel.cs
namespace CoreBB.Web.Models.User
{
    using CoreBB.Web.Data.Models;
    using System;
    using System.ComponentModel;

    public class UserEditViewModel
    {
        [DisplayName("ID")]
        public int Id { get; set; }
        [DisplayName("Name")]
        public string Name { get; set; }
        [DisplayName("Current Password")]
        public string CurrentPassword { get; set; }
        [DisplayName("New Password")]
        public string Password { get; set; }
        [DisplayName("New Password Again")]
        public string RepeatPassword { get; set; }
        [DisplayName("Description")]
        public string Description { get; set; }
        [DisplayName("Administrator")]
        public bool IsAdministrator { get; set; }
        [DisplayName("Lock")]
        public bool IsLocked { get; set; }
        [DisplayName("Register Date")]
        public DateTime RegisterDateTime { get; set; }
        [DisplayName("Last Log In Date")]
        public DateTime LastLogInDateTime { get; set; }

        public static UserEditViewModel FromUser(User user)
        {
            var model = new UserEditViewModel();
            model.Id = user.Id;
            model.Name = user.Name;
            model.Description = user.Description;
            model.IsAdministrator = user.IsAdministrator;
            model.IsLocked = user.IsLocked;
            model.RegisterDateTime = user.RegisterDateTime;
            model.LastLogInDateTime = user.LastLogInDateTime;
            return model;
        }
    }
}

CoreBB/Controllers/MessageController.cs
namespace CoreBB.Web.Controllers
{
    using System;
    using System.Linq;
    using System.Threading.Tasks;
    using CoreBB.Web.Data;
    using CoreBB.Web.Data.Models;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.EntityFrameworkCore;

    [Authorize]
    public class MessageController : Controller
    {
        private CoreBBContext _dbContext;

        public MessageController(CoreBBContext dbContext)
        {
            _dbContext = dbContext;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var user = _dbContext.User.SingleOrDefault(u => u.Name == User.Identity.Name);
            var messages = _dbContext.Message.Include("ToUser").Include("FromUser")
                .Where(m => m.ToUserId == user.Id || m.FromUserId == user.Id);
            return View(messages);
        }

        [HttpGet]
        public IActionResult Create(string toUserName)
        {
            var toUser = _dbContext.User.SingleOrDefault(u => u.Name == toUserName);
            if (toUser == null)
            {
                throw new Exception("User does not exist.");
            }

            var message = new Message { ToUserId = toUser.Id, ToUser = toUser };
            return View(message);
        }

        [HttpPost]
        public async Task<IActionResult> Create(Message model)
        {
            if (!ModelState.IsValid)
            {
                throw new Exception("Invalide messasge information.");
            }

            var fromUser = _dbContext.User.SingleOrDefault(u => u.Name == User.Identity.Name);
            model.FromUserId = fromUser.Id;
            model.SendDateTime = DateTime.Now;
            await _dbContext.Message.AddAsync(model);
            await _dbContext.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Detail(int id)
        {
            var message = _dbContext.Message.Include("ToUser").Include("FromUser")
                .SingleOrDefault(m => m.Id == id);
            if (message == null)
            {
                throw new Exception("Message does not exist.");
            }

            var user = _dbContext.User.SingleOrDefault(u => u.Name == User.Identity.Name);
            if (message.ToUserId != user.Id && message.FromUserId != user.Id)
            {
                throw new Exception("Message access denied.");
            }

            if (message.ToUserId == user.Id)
            {
                message.IsRead = true;
            }

            _dbContext.Message.Update(message);
            await _dbContext.SaveChangesAsync();
            return View(message);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var message = _dbContext.Message.SingleOrDefault(m => m.Id == id);
            if (message == null)
            {
                throw new Exception("Message does not exist.");
            }

            var user = _dbContext.User.SingleOrDefault(u => u.Name == User.Identity.Name);
            if (message.ToUserId != user.Id && message.FromUserId != user.Id)
            {
                throw new Exception("Message access denied.");
            }

            _dbContext.Message.Remove(message);
            await _dbContext.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

CoreBB/Controllers/UserController.cs
namespace CoreBB.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Security.Claims;
    using System.Threading.Tasks;
    using CoreBB.Web.Data;
    using CoreBB.Web.Data.Models;
    using CoreBB.Web.Models.User;
    using Microsoft.AspNetCore.Authentication;
    using Microsoft.AspNetCore.Authentication.Cookies;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;


    [Authorize]
    public class UserController : Controller
    {
        private CoreBBContext _dbContext;

        public UserController(CoreBBContext dbContext)
        {
            _dbContext = dbContext;
        }

        [AllowAnonymous, HttpGet]
        public async Task<IActionResult> Register()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return View();
        }

        [AllowAnonymous, HttpPost]
        public async Task<IActionResult> Register(RegisterViewModel model)
        {
            if (!ModelState.IsValid)
            {
                throw new Exception("Invalid registration information.");
            }

            model.Name = model.Name.Trim();
            model.Password = model.Password.Trim();
            model.RepeatPassword = model.RepeatPassword.Trim();

            var targetUser = _dbContext.User
                .SingleOrDefault(u => u.Name == model.Name);

            if (targetUser != null)
            {
                throw new Exception("User name already exists.");
            }

            if (!model.Password.Equals(model.RepeatPassword))
            {
                throw new Exception("Passwords are not identical.");
            }

            var hasher = new PasswordHasher<User>();
            targetUser = new User { Name = model.Name, RegisterDateTime = DateTime.Now, Description = model.Description };
            targetUser.PasswordHash = hasher.HashPassword(targetUser, model.Password);

            if (_dbContext.User.Count() == 0)
            {
                targetUser.IsAdministrator = true;
            }

            await _dbContext.User.AddAsync(targetUser);
            await _dbContext.SaveChangesAsync();

            await LogInUserAsync(targetUser);

            return RedirectToAction("Index", "Home");
        }

        private async Task LogInUserAsync(User user)
        {
            var claims = new List<Claim>();
            claims.Add(new Claim(ClaimTypes.Name, user.Name));
            if (user.IsAdministrator)
            {
                claims.Add(new Claim(ClaimTypes.Role, Roles.Administrator));
            }

            var claimsIndentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
            var claimsPrincipal = new ClaimsPrincipal(claimsIndentity);
            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, claimsPrincipal);
            user.LastLogInDateTime = DateTime.Now;
            await _dbContext.SaveChangesAsync();
        }

        [AllowAnonymous, HttpGet]
        public async Task<IActionResult> LogIn()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return View();
        }

        [AllowAnonymous, HttpPost]
        public async Task<IActionResult> LogIn(LogInViewModel model)
        {
            if (!ModelState.IsValid)
            {
                throw new Exception("Invalid user information.");
            }

            var targetUser = _dbContext.User.SingleOrDefault(u => u.Name.Equals(model.Name, StringComparison.CurrentCultureIgnoreCase));
            if (targetUser == null)
            {
                throw new Exception("User does not exist.");
            }

            var hasher = new PasswordHasher<User>();
            var result = hasher.VerifyHashedPassword(targetUser, targetUser.PasswordHash, model.Password);
            if (result != PasswordVerificationResult.Success)
            {
                throw new Exception("The password is wrong.");
            }

            await LogInUserAsync(targetUser);
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public async Task<IActionResult> LogOut()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public IActionResult Detail(string name)
        {
            var user = _dbContext.User.SingleOrDefault(u => u.Name == name);
            if (user == null)
            {
                throw new Exception($"User '{name}' does not exist.");
            }

            return View(user);
        }

        [HttpGet]
        public IActionResult Edit(string name)
        {
            if (User.Identity.Name != name && !User.IsInRole(Roles.Administrator))
            {
                throw new Exception("Operation is denied.");
            }

            var user = _dbContext.User.SingleOrDefault(u => u.Name == name);
            if (user == null)
            {
                throw new Exception($"User '{name}' does not exist.");
            }

            var model = UserEditViewModel.FromUser(user);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(UserEditViewModel model)
        {
            if (!ModelState.IsValid)
            {
                throw new Exception("Invalid user information.");
            }

            var user = _dbContext.User
                .SingleOrDefault(u => u.Name.Equals(model.Name, StringComparison.CurrentCultureIgnoreCase));

            if (user == null)
            {
                throw new Exception("User does not exist.");
            }

            if (!string.IsNullOrEmpty(model.Password))
            {
                model.Password = model.Password.Trim();
                model.RepeatPassword = model.RepeatPassword.Trim();
                if (!model.Password.Equals(model.RepeatPassword))
                {
                    throw new Exception("Passwords are not identical.");
                }

                var hasher = new PasswordHasher<User>();
                if (!User.IsInRole(Roles.Administrator))
                {
                    var vr = hasher.VerifyHashedPassword(user, user.PasswordHash, model.CurrentPassword);
                    if (vr != PasswordVerificationResult.Success)
                    {
                        throw new Exception("Please provide correct current password.");
                    }
                }

                user.PasswordHash = hasher.HashPassword(user, model.Password);
            }

            user.Description = model.Description;

            if (User.IsInRole(Roles.Administrator))
            {
                user.IsAdministrator = model.IsAdministrator;
                user.IsLocked = model.IsLocked;
            }

            _dbContext.User.Update(user);
            await _dbContext.SaveChangesAsync();

            return RedirectToAction("Detail", new { name = user.Name });
        }

        [HttpGet, Authorize(Roles = Roles.Administrator)]
        public IActionResult Index()
        {
            var users = _dbContext.User.ToList();
            return View(users);
        }
    }
}

CoreBB/Views/User/Detail.cshtml
@using CoreBB.Web.Data.Models
@model User
@{
    ViewBag.Title = "User Detail";
}
<div class="container col-6 offset-3" style="margin-top:120px">
    <div class="card border-info">
        <div class="card-header text-white bg-info">
            <strong>User Detail Information</strong>
        </div>
        <div class="card-body">
            <table class="table table-bordered table-striped">
                <tr>
                    <th>Property</th>
                    <th>Value</th>
                </tr>
                <tr>
                    <td><strong>ID</strong></td>
                    <td>@Model.Id</td>
                </tr>
                <tr>
                    <td><strong>Name</strong></td>
                    <td>@Model.Name</td>
                </tr>
                <tr>
                    <td><strong>Description</strong></td>
                    <td>@Model.Description</td>
                </tr>
                <tr>
                    <td><strong>Administrator</strong></td>
                    <td><input type="checkbox" asp-for="IsAdministrator" disabled="disabled" /></td>
                </tr>
                <tr>
                    <td><strong>Locked</strong></td>
                    <td><input type="checkbox" asp-for="IsLocked" disabled="disabled" /></td>
                </tr>
                <tr>
                    <td><strong>Register Date</strong></td>
                    <td>@Model.RegisterDateTime.ToShortDateString()</td>
                </tr>
                <tr>
                    <td><strong>Last Login</strong></td>
                    <td>@Model.LastLogInDateTime.ToShortDateString()</td>
                </tr>
                <tr>
                    <td><strong>Operation</strong></td>
                    <td>
                        @if (User.IsInRole(Roles.Administrator) || User.Identity.Name == Model.Name)
                        {
                            <a class="btn-sm btn-primary" asp-action="Edit" asp-route-name="@Model.Name">Update</a>
                        }
                        <a class="btn-sm btn-warning" asp-controller="Message" asp-action="Create" asp-route-tousername="@Model.Name">Send Message</a>
                    </td>
                </tr>
            </table>
        </div>
    </div>
</div>

CoreBB/Views/User/Edit.cshtml
@using CoreBB.Web.Models.User
@model UserEditViewModel
@{
    ViewBag.Title = "Update User";
}
<form asp-action="Edit" method="post">
    <input type="hidden" asp-for="Id" />
    <input type="hidden" asp-for="Name" />
    <input type="hidden" asp-for="RegisterDateTime" />
    <input type="hidden" asp-for="LastLogInDateTime" />

    <div class="container col-6 offset-3" style="margin-top:120px">
        <div class="card border-info">
            <div class="card-header text-white bg-info">
                <strong>Update User</strong>
            </div>
            <div class="card-body">
                <table class="table table-bordered table-striped">
                    <tr>
                        <th>Property</th>
                        <th>Value</th>
                    </tr>
                    <tr>
                        <td><strong>ID</strong></td>
                        <td>@Model.Id</td>
                    </tr>
                    <tr>
                        <td><strong>Name</strong></td>
                        <td>@Model.Name</td>
                    </tr>
                    @if (!User.IsInRole(CoreBB.Web.Data.Models.Roles.Administrator))
                    {
                        <tr>
                            <td><strong>Current Password</strong></td>
                            <td><input class="form-control" type="password" asp-for="CurrentPassword" /></td>
                        </tr>
                    }
                    <tr>
                        <td><strong>New Password</strong></td>
                        <td><input class="form-control" type="password" asp-for="Password" /></td>
                    </tr>
                    <tr>
                        <td><strong>Repeat New Password</strong></td>
                        <td><input class="form-control" type="password" asp-for="RepeatPassword" /></td>
                    </tr>
                    <tr>
                        <td><strong>Description</strong></td>
                        <td><textarea class="form-control" asp-for="Description"></textarea></td>
                    </tr>
                    @if (User.IsInRole(CoreBB.Web.Data.Models.Roles.Administrator) && User.Identity.Name != Model.Name)
                    {
                        <tr>
                            <td><strong>Administrator</strong></td>
                            <td><input type="checkbox" asp-for="IsAdministrator" /></td>
                        </tr>
                        <tr>
                            <td><strong>Locked</strong></td>
                            <td><input type="checkbox" asp-for="IsLocked" /></td>
                        </tr>
                    }
                    <tr>
                        <td><strong>Register Date</strong></td>
                        <td>@Model.RegisterDateTime.ToShortDateString()</td>
                    </tr>
                    <tr>
                        <td><strong>Last Login</strong></td>
                        <td>@Model.LastLogInDateTime.ToShortDateString()</td>
                    </tr>
                    <tr>
                        <td><strong>Update</strong></td>
                        <td><input type="submit" class="btn-sm btn-success" value="Update" /></td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</form>

CoreBB/Views/User/Index.cshtml
@model IEnumerable<CoreBB.Web.Data.Models.User>
@{
    ViewBag.Title = "Users";
}
<div class="container" style="margin-top:60px">
    <div class="card border-info">
        <div class="card-header text-white bg-info">
            <strong>Users</strong><span>&nbsp;-&nbsp;Total:@Model.Count()</span>
        </div>
        <div class="card-body">
            <table class="table table-bordered table-striped table-hover">
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Register</th>
                    <th>Last Login</th>
                    <th>Administrator</th>
                    <th>Locked</th>
                    <th>Operation</th>
                </tr>
                @foreach (var u in Model)
                {
                    <tr>
                        <td>@u.Id</td>
                        <td><a asp-controller="User" asp-action="Detail" asp-route-name="@u.Name">@u.Name</a></td>
                        <td>@u.RegisterDateTime.ToShortDateString()</td>
                        <td>@u.LastLogInDateTime.ToShortDateString()</td>
                        <td><input type="checkbox" disabled="disabled" asp-for="@u.IsAdministrator" /></td>
                        <td><input type="checkbox" disabled="disabled" asp-for="@u.IsLocked" /></td>
                        <td><a class="btn-sm btn-primary" asp-controller="User" asp-action="Detail" asp-route-name="@u.Name">Detail</a></td>
                    </tr>
                }
            </table>
        </div>
    </div>
</div>

CoreBB/Views/User/LogIn.cshtml
@{
    ViewData["Title"] = "LogIn";
}

<h1>LogIn</h1>

@model CoreBB.Web.Models.User.LogInViewModel

@{
    ViewBag.Title = "Login";
}

<div class="container col-4 offset-4" style="margin-top:120px">
    <div class="card border-info">
        <div class="card-header text-white bg-info">
            <strong>Login</strong>
        </div>
        <div class="card-body">
            <form asp-action="LogIn" method="post">
                <div class="form-group">
                    <label asp-for="Name"></label>
                    <input class="form-control" asp-for="Name" />
                </div>
                <div class="form-group">
                    <label asp-for="Password"></label>
                    <input class="form-control" asp-for="Password" type="password" />
                </div>
                <input type="submit" class="btn btn-primary float-right" value="Log In" />
            </form>
        </div>
    </div>
</div>

CoreBB/Views/User/Register.cshtml
@model CoreBB.Web.Models.User.RegisterViewModel
@{
    ViewBag.Title = "Register";
}

<div class="container col-4 offset-4" style="margin-top:120px">
    <div class="card border-info">
        <div class="card-header text-white bg-info">
            <strong>Register</strong>
        </div>
        <div class="card-body">
            <form asp-action="Register" method="post">
                <div class="form-group">
                    <label asp-for="Name"></label>
                    <input class="form-control" asp-for="Name" />
                </div>
                <div class="form-group">
                    <label asp-for="Password"></label>
                    <input class="form-control" asp-for="Password" type="password" />
                </div>
                <div class="form-group">
                    <label asp-for="RepeatPassword"></label>
                    <input class="form-control" asp-for="RepeatPassword" type="password" />
                </div>
                <div class="form-group">
                    <label asp-for="Description"></label>
                    <textarea class="form-control" style="min-height:120px" asp-for="Description"></textarea>
                </div>
                <input type="submit" class="btn btn-primary float-right" value="Register" />
            </form>
        </div>
    </div>
</div>