CoreBB/Controllers/ForumController.cs
namespace CoreBB.Web.Controllers
{
    using System;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.EntityFrameworkCore;
    using CoreBB.Web.Data.Models;
    using CoreBB.Web.Data;

    [Authorize]
    public class ForumController : Controller
    {
        private CoreBBContext _dbContext;

        public ForumController(CoreBBContext dbContext)
        {
            _dbContext = dbContext;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var forums = _dbContext.Forum.Include("Owner").ToList();
            return View(forums);
        }

        [HttpGet, Authorize(Roles = Roles.Administrator)]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost, Authorize(Roles = Roles.Administrator)]
        public async Task<IActionResult> Create(Forum model)
        {
            if (!ModelState.IsValid)
            {
                throw new Exception("Invalid forum information.");
            }

            model.OwnerId = _dbContext.User.SingleOrDefault(u => u.Name == User.Identity.Name).Id;
            model.CreateDateTime = DateTime.Now;
            await _dbContext.Forum.AddAsync(model);
            await _dbContext.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Detail(int id)
        {
            var forum = _dbContext.Forum.Include("Owner").SingleOrDefault(f => f.Id == id);
            if (forum == null)
            {
                throw new Exception("Forum does not exist.");
            }

            return View(forum);
        }

        [HttpGet, Authorize(Roles = Roles.Administrator)]
        public IActionResult Delete(int id)
        {
            var forum = _dbContext.Forum.Include("Owner").SingleOrDefault(f => f.Id == id);
            if (forum == null)
            {
                throw new Exception("Forum does not exist.");
            }

            return View(forum);
        }

        [HttpPost, Authorize(Roles = Roles.Administrator)]
        public async Task<IActionResult> Delete(Forum model)
        {
            var forum = _dbContext.Forum.SingleOrDefault(f => f.Id == model.Id);
            if (forum == null)
            {
                throw new Exception("Forum does not exist.");
            }

            _dbContext.Forum.Remove(forum);
            await _dbContext.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpGet, Authorize(Roles = Roles.Administrator)]
        public IActionResult Edit(int id)
        {
            var forum = _dbContext.Forum.Include("Owner").SingleOrDefault(f => f.Id == id);
            if (forum == null)
            {
                throw new Exception("Forum does not exist.");
            }

            return View(forum);
        }

        [HttpPost, Authorize(Roles = Roles.Administrator)]
        public async Task<IActionResult> Edit(Forum model)
        {
            if (!ModelState.IsValid)
            {
                throw new Exception("Invalid forum information.");
            }

            _dbContext.Forum.Update(model);
            await _dbContext.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

CoreBB/Controllers/TopicController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;
using CoreBB.Web.Data.Models;
using CoreBB.Web.Data;

namespace CoreBB.Web.Controllers
{

    [Authorize]
    public class TopicController : Controller
    {

        private CoreBBContext _dbContext;

        public TopicController(CoreBBContext dbContext)
        {
            _dbContext = dbContext;
        }

        [HttpGet]
        public IActionResult Index(int forumId)
        {
            var forum = _dbContext.Forum.Include("Owner").SingleOrDefault(f => f.Id == forumId);
            if (forum == null)
            {
                throw new Exception("Forum does not exist.");
            }

            forum.Topic = _dbContext.Topic.Include("Owner")
                .Where(t => t.ForumId == forumId && t.ReplyToTopicId == null).ToList();
            return View(forum);
        }

        [HttpGet]
        public IActionResult Create(int forumId)
        {
            var forum = _dbContext.Forum.SingleOrDefault(f => f.Id == forumId);
            if (forum == null)
            {
                throw new Exception("Forum does not exist.");
            }

            if (forum.IsLocked)
            {
                throw new Exception("This forum is locked.");
            }

            var topic = new Topic { ForumId = forumId };
            return View(topic);
        }

        [HttpPost]
        public async Task<IActionResult> Create(Topic model)
        {
            if (!ModelState.IsValid)
            {
                throw new Exception("Invalid topic information.");
            }

            var user = _dbContext.User.SingleOrDefault(u => u.Name == User.Identity.Name);
            model.OwnerId = user.Id;
            model.PostDateTime = DateTime.Now;
            await _dbContext.Topic.AddAsync(model);
            await _dbContext.SaveChangesAsync();
            model.RootTopicId = model.Id;
            _dbContext.Topic.Update(model);
            await _dbContext.SaveChangesAsync();

            return RedirectToAction("Index", new { forumId = model.ForumId });
        }

        [HttpGet]
        public IActionResult Detail(int id)
        {
            var rootTopic = _dbContext.Topic.Include("Owner").Include("ModifiedByUser")
                .SingleOrDefault(t => t.Id == id);
            if (rootTopic == null)
            {
                throw new Exception("Topic does not exist.");
            }

            rootTopic.InverseReplyToTopic = _dbContext.Topic.Include("Owner").Include("ModifiedByUser")
                .Where(t => t.RootTopicId == id && t.ReplyToTopicId != null).ToList();
            return View(rootTopic);
        }

        [HttpGet]
        public IActionResult Reply(int toId)
        {
            var toTopic = _dbContext.Topic.SingleOrDefault(t => t.Id == toId);
            if (toTopic == null)
            {
                throw new Exception("The topic does not exist.");
            }

            if (toTopic.IsLocked)
            {
                throw new Exception("The topic is locked.");
            }

            var topic = new Topic
            {
                ReplyToTopicId = toTopic.Id,
                RootTopicId = toTopic.RootTopicId,
                ForumId = toTopic.ForumId,
                ReplyToTopic = toTopic
            };

            return View(topic);
        }

        [HttpPost]
        public async Task<IActionResult> Reply(Topic model)
        {
            if (!ModelState.IsValid)
            {
                throw new Exception("Invalid topic information.");
            }

            var user = _dbContext.User.SingleOrDefault(u => u.Name == User.Identity.Name);
            model.OwnerId = user.Id;
            model.PostDateTime = DateTime.Now;
            await _dbContext.Topic.AddAsync(model);
            await _dbContext.SaveChangesAsync();

            return RedirectToAction("Index", new { forumId = model.ForumId });
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var topic = _dbContext.Topic.Include("Owner").Include("ModifiedByUser")
                .SingleOrDefault(t => t.Id == id);
            if (topic == null)
            {
                throw new Exception("Topic does not exist.");
            }

            var user = _dbContext.User.SingleOrDefault(u => u.Name == User.Identity.Name);
            if (!(topic.OwnerId == user.Id || User.IsInRole(Roles.Administrator)))
            {
                throw new Exception("Update topic denied.");
            }

            return View(topic);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Topic model)
        {
            if (!ModelState.IsValid)
            {
                throw new Exception("Invalid topic information.");
            }

            var user = _dbContext.User.SingleOrDefault(u => u.Name == User.Identity.Name);
            model.ModifiedByUserId = user.Id;
            model.ModifyDateTime = DateTime.Now;
            _dbContext.Topic.Update(model);
            await _dbContext.SaveChangesAsync();

            return RedirectToAction("Index", new { forumId = model.ForumId });
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var topic = _dbContext.Topic.SingleOrDefault(t => t.Id == id);
            if (topic == null)
            {
                throw new Exception("Topic does not exist.");
            }

            var user = _dbContext.User.SingleOrDefault(u => u.Name == User.Identity.Name);
            if (!(topic.OwnerId == user.Id || User.IsInRole(Roles.Administrator)))
            {
                throw new Exception("You are not authroized to delete this topic.");
            }

            return View(topic);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(Topic model)
        {
            if (!ModelState.IsValid)
            {
                throw new Exception("Invalid topic information.");
            }

            var topic = _dbContext.Topic.SingleOrDefault(t => t.Id == model.Id);
            if (topic == null)
            {
                throw new Exception("Topic does not exist.");
            }

            var user = _dbContext.User.SingleOrDefault(u => u.Name == User.Identity.Name);
            if (!(topic.OwnerId == user.Id || User.IsInRole(Roles.Administrator)))
            {
                throw new Exception("You are not authroized to delete this topic.");
            }

            _dbContext.Topic.Remove(topic);
            if (topic.Id == topic.RootTopicId)
            {
                var descendants = _dbContext.Topic.Where(t => t.RootTopicId == topic.Id);
                _dbContext.Topic.RemoveRange(descendants);
            }
            await _dbContext.SaveChangesAsync();

            return RedirectToAction("Index", new { forumId = topic.ForumId });
        }
    }
}

CoreBB/Controllers/UserController.cs
namespace CoreBB.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Security.Claims;
    using System.Threading.Tasks;
    using CoreBB.Web.Data;
    using CoreBB.Web.Data.Models;
    using CoreBB.Web.Models.User;
    using Microsoft.AspNetCore.Authentication;
    using Microsoft.AspNetCore.Authentication.Cookies;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;


    [Authorize]
    public class UserController : Controller
    {
        private CoreBBContext _dbContext;

        public UserController(CoreBBContext dbContext)
        {
            _dbContext = dbContext;
        }

        [AllowAnonymous, HttpGet]
        public async Task<IActionResult> Register()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return View();
        }

        [AllowAnonymous, HttpPost]
        public async Task<IActionResult> Register(RegisterViewModel model)
        {
            if (!ModelState.IsValid)
            {
                throw new Exception("Invalid registration information.");
            }

            model.Name = model.Name.Trim();
            model.Password = model.Password.Trim();
            model.RepeatPassword = model.RepeatPassword.Trim();

            var targetUser = _dbContext.User
                .SingleOrDefault(u => u.Name == model.Name);

            if (targetUser != null)
            {
                throw new Exception("User name already exists.");
            }

            if (!model.Password.Equals(model.RepeatPassword))
            {
                throw new Exception("Passwords are not identical.");
            }

            var hasher = new PasswordHasher<User>();
            targetUser = new User { Name = model.Name, RegisterDateTime = DateTime.Now, Description = model.Description };
            targetUser.PasswordHash = hasher.HashPassword(targetUser, model.Password);

            if (_dbContext.User.Count() == 0)
            {
                targetUser.IsAdministrator = true;
            }

            await _dbContext.User.AddAsync(targetUser);
            await _dbContext.SaveChangesAsync();

            await LogInUserAsync(targetUser);

            return RedirectToAction("Index", "Home");
        }

        private async Task LogInUserAsync(User user)
        {
            var claims = new List<Claim>();
            claims.Add(new Claim(ClaimTypes.Name, user.Name));
            if (user.IsAdministrator)
            {
                claims.Add(new Claim(ClaimTypes.Role, Roles.Administrator));
            }

            var claimsIndentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
            var claimsPrincipal = new ClaimsPrincipal(claimsIndentity);
            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, claimsPrincipal);
            user.LastLogInDateTime = DateTime.Now;
            await _dbContext.SaveChangesAsync();
        }

        [AllowAnonymous, HttpGet]
        public async Task<IActionResult> LogIn()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return View();
        }

        [AllowAnonymous, HttpPost]
        public async Task<IActionResult> LogIn(LogInViewModel model)
        {
            if (!ModelState.IsValid)
            {
                throw new Exception("Invalid user information.");
            }

            var targetUser = _dbContext.User.SingleOrDefault(u => u.Name.Equals(model.Name, StringComparison.CurrentCultureIgnoreCase));
            if (targetUser == null)
            {
                throw new Exception("User does not exist.");
            }

            var hasher = new PasswordHasher<User>();
            var result = hasher.VerifyHashedPassword(targetUser, targetUser.PasswordHash, model.Password);
            if (result != PasswordVerificationResult.Success)
            {
                throw new Exception("The password is wrong.");
            }

            await LogInUserAsync(targetUser);
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public async Task<IActionResult> LogOut()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public IActionResult Detail(string name)
        {
            var user = _dbContext.User.SingleOrDefault(u => u.Name == name);
            if (user == null)
            {
                throw new Exception($"User '{name}' does not exist.");
            }

            return View(user);
        }

        [HttpGet]
        public IActionResult Edit(string name)
        {
            if (User.Identity.Name != name && !User.IsInRole(Roles.Administrator))
            {
                throw new Exception("Operation is denied.");
            }

            var user = _dbContext.User.SingleOrDefault(u => u.Name == name);
            if (user == null)
            {
                throw new Exception($"User '{name}' does not exist.");
            }

            var model = UserEditViewModel.FromUser(user);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(UserEditViewModel model)
        {
            if (!ModelState.IsValid)
            {
                throw new Exception("Invalid user information.");
            }

            var user = _dbContext.User
                .SingleOrDefault(u => u.Name.Equals(model.Name, StringComparison.CurrentCultureIgnoreCase));

            if (user == null)
            {
                throw new Exception("User does not exist.");
            }

            if (!string.IsNullOrEmpty(model.Password))
            {
                model.Password = model.Password.Trim();
                model.RepeatPassword = model.RepeatPassword.Trim();
                if (!model.Password.Equals(model.RepeatPassword))
                {
                    throw new Exception("Passwords are not identical.");
                }

                var hasher = new PasswordHasher<User>();
                if (!User.IsInRole(Roles.Administrator))
                {
                    var vr = hasher.VerifyHashedPassword(user, user.PasswordHash, model.CurrentPassword);
                    if (vr != PasswordVerificationResult.Success)
                    {
                        throw new Exception("Please provide correct current password.");
                    }
                }

                user.PasswordHash = hasher.HashPassword(user, model.Password);
            }

            user.Description = model.Description;

            if (User.IsInRole(Roles.Administrator))
            {
                user.IsAdministrator = model.IsAdministrator;
                user.IsLocked = model.IsLocked;
            }

            _dbContext.User.Update(user);
            await _dbContext.SaveChangesAsync();

            return RedirectToAction("Detail", new { name = user.Name });
        }

        [HttpGet, Authorize(Roles = Roles.Administrator)]
        public IActionResult Index()
        {
            var users = _dbContext.User.ToList();
            return View(users);
        }
    }
}

CoreBB/Views/Shared/_ForumDetail.cshtml
@using CoreBB.Web.Data.Models
@model Forum
<div class="container col-6 offset-3" style="margin-top:120px">
    <div class="card border-info">
        <div class="card-header text-white bg-info">
            <strong>Forum Detail Information</strong>
        </div>
        <div class="card-body">
            <table class="table table-bordered table-striped">
                <tr>
                    <th>Property</th>
                    <th>Value</th>
                </tr>
                <tr>
                    <td><strong>ID</strong></td>
                    <td>@Model.Id</td>
                </tr>
                <tr>
                    <td><strong>Name</strong></td>
                    <td>@Model.Name</td>
                </tr>
                <tr>
                    <td><strong>Owner</strong></td>
                    <td><a asp-action="Detail" asp-controller="User" asp-route-name="@Model.Owner.Name">@Model.Owner.Name</a></td>
                </tr>
                <tr>
                    <td><strong>Description</strong></td>
                    <td>@Model.Description</td>
                </tr>
                <tr>
                    <td><strong>Locked</strong></td>
                    <td><input type="checkbox" asp-for="IsLocked" disabled="disabled" /></td>
                </tr>
                <tr>
                    <td><strong>Create Date</strong></td>
                    <td>@Model.CreateDateTime.ToShortDateString()</td>
                </tr>
                <tr>
                    <td><strong>Operation</strong></td>
                    <td>
                        @if (ViewData["Mode"] == "ShowingDetail")
                        {
                            @if (User.IsInRole(Roles.Administrator))
                            {
                                <a class="btn-sm btn-primary" asp-action="Edit" asp-route-id="@Model.Id">Update</a>
                                <a class="btn-sm btn-warning" asp-action="Delete" asp-route-id="@Model.Id">Delete</a>
                            }
                            <a class="btn-sm btn-success" asp-controller="Topic" asp-action="Create" asp-route-forumid="@Model.Id">Post Topic</a>
                        }
                        @if (ViewData["Mode"] == "ConfirmingDelete")
                        {
                            <input type="submit" class="btn-sm btn-warning" value="Confirm" />
                        }
                    </td>
                </tr>
            </table>
        </div>
    </div>
</div>

CoreBB/Views/Shared/_Layout.cshtml
@using CoreBB.Web.Data.Models
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <script src="~/Content/jQuery/jquery-3.5.1.js"></script>
    <script src="~/Content/Bootstrap/js/bootstrap.js"></script>
    <script src="~/Content/Bootstrap/js/bootstrap.bundle.js"></script>
    <link href="~/Content/Bootstrap/css/bootstrap.css" rel="stylesheet" />
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" asp-action="Index" asp-controller="Home">CoreBB</a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" asp-action="Index" asp-controller="Home">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-action="Index" asp-controller="Forum">Forums</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-action="Index" asp-controller="Message">Messages</a>
                </li>
                @if (User.IsInRole(Roles.Administrator))
                {
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Manage
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" asp-controller="User" asp-action="Index">Users</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" asp-controller="Forum" asp-action="Create">Create Forum</a>
                        </div>
                    </li>
                }
            </ul>
            <div class="pull-right">
                @if (!User.Identity.IsAuthenticated)
                {
                    <div class="btn-group btn-group-sm">
                        <a class="btn btn-secondary btn-info" asp-controller="User" asp-action="LogIn">Log In</a>
                        <a class="btn btn-secondary btn-info" asp-controller="User" asp-action="Register">Register</a>
                    </div>
                }
                else
                {
                    <div class="btn-group btn-group-sm">
                        <a class="btn btn-secondary btn-info" asp-controller="User" asp-action="Detail" asp-route-name="@User.Identity.Name">
                            My Account
                        </a>
                        <a class="btn btn-secondary btn-info" asp-controller="User" asp-action="LogOut">Log Out</a>
                    </div>
                }
            </div>
        </div>
    </nav>
    <div class="container">
        @RenderBody()
    </div>
    <hr />
    <footer>
        <p>&copy; 2020 - CoreBB</p>
    </footer>
</body>
</html>

CoreBB/Views/Shared/_MessageList.cshtml
@model IEnumerable<CoreBB.Web.Data.Models.Message>
<table class="table table-bordered table-striped table-hover">
    <tr>
        <th>From</th>
        <th>To</th>
        <th>Date</th>
        <th>Read</th>
        <th>Title</th>
        <th>Operation</th>
    </tr>
    @foreach (var m in Model)
    {
        <tr>
            <td><a asp-controller="User" asp-action="Detail" asp-route-name="@m.FromUser.Name">@m.FromUser.Name</a></td>
            <td><a asp-controller="User" asp-action="Detail" asp-route-name="@m.ToUser.Name">@m.ToUser.Name</a></td>
            <td>@m.SendDateTime.ToShortDateString()</td>
            <td><input type="checkbox" disabled="disabled" asp-for="@m.IsRead" /></td>
            <td><a asp-action="Detail" asp-route-id="@m.Id">@m.Title</a></td>
            <td>
                <a class="btn-sm btn-primary" asp-action="Detail" asp-route-id="@m.Id">Read</a>
                <a class="btn-sm btn-warning" asp-action="Delete" asp-route-id="@m.Id">Delete</a>
            </td>
        </tr>
    }
</table>

CoreBB/Views/Shared/_TopicEditing.cshtml
@model CoreBB.Web.Data.Models.Topic
<div class="container col-6 offset-3" style="margin-top:120px">
    <div class="card border-info">
        <div class="card-header text-white bg-info">
            <strong>@ViewData["Mode"]</strong>
        </div>
        <div class="card-body">
            <div class="form-group">
                <label asp-for="Title"></label>
                <input class="form-control" asp-for="Title" />
            </div>
            <div class="form-group">
                <label asp-for="Content"></label>
                <textarea class="form-control" style="min-height:120px" asp-for="Content"></textarea>
            </div>
            <div class="form-group">
                <span>Lock</span>
                <input type="checkbox" asp-for="IsLocked" />
            </div>
        </div>
        <div class="card-footer">
            <input type="submit" class="btn-sm btn-success" value="@ViewData["SubmitButtonText"]" />
        </div>
    </div>
</div>

CoreBB/Views/Shared/_TopicReading.cshtml
@using CoreBB.Web.Data.Models
@model Topic
<div class="container">
    <div class="card border-info">
        <div class="card-header">
            <strong>@Model.Title</strong>
            [Posted by <a asp-controller="User" asp-action="Detail" asp-route-name="@Model.Owner.Name">@Model.Owner.Name</a> at @Model.PostDateTime.ToShortDateString()]
            [Modified by <a asp-controller="User" asp-action="Detail" asp-route-name="@(Model.ModifiedByUser?.Name ?? "N/A")">@(Model.ModifiedByUser?.Name ?? "N/A")</a> at @(Model.ModifyDateTime?.ToShortDateString() ?? "N/A")]
        </div>
        <div class="card-body">
            <p>@Model.Content</p>
        </div>
        <div class="card-footer">
            @if (!Model.IsLocked)
            {
                <a class="btn-sm btn-success" asp-action="Reply" asp-controller="Topic" asp-route-toid="@Model.Id">Reply</a>
            }
            @if (Model.Owner.Name == User.Identity.Name || User.IsInRole(Roles.Administrator))
            {
                <a class="btn-sm btn-warning" asp-action="Edit" asp-controller="Topic" asp-route-id="@Model.Id">Edit</a>
                <a class="btn-sm btn-danger" asp-action="Delete" asp-controller="Topic" asp-route-id="@Model.Id">Delete</a>
            }
        </div>
    </div>
</div>